services:
  postgres:
    image: postgres:16
    container_name: postgres_tobias
    restart: always
    environment:
      POSTGRES_DB: tobias
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d

  mysql:
    image: mysql:8.3
    container_name: mysql_tobias
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init/mysql:/docker-entrypoint-initdb.d


volumes:
  postgres_data:
  mysql_data: