from pydantic import BaseModel
from typing import Optional

# Request model for creating/updating ScoreCard
class ScoreCardCreate(BaseModel):
    ScoreCardId: Optional[int] = None  # Allow manual input or leave blank
    Name: str
    VariableId: int
    FixedValue: Optional[str] = None
    StartRange: Optional[float] = None
    EndRange: Optional[float] = None
    Coefficient: Optional[float] = None
    Type: Optional[str] = None
    IsExcel: Optional[bool] = False

# Response model for returning ScoreCard data



class ScoreCardUpdate(ScoreCardCreate):
    pass

class ScoreCardResponse(ScoreCardCreate):
    id: int  # ID is auto-generated by the database

    class Config:
        orm_mode = True

